"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowLeftIcon, LockIcon } from "lucide-react";

import { CARD, CTA_SECONDARY, FOCUS, IconCircle } from "@/components/dashboard/ui";
import { PlanProvider, usePlanContext } from "@/lib/context/plan-context";
import { PlanNav } from "@/components/plan/plan-nav";
import { cn } from "@/lib/utils";

/** Bloque de esqueleto: pulso suave que respeta prefers-reduced-motion. */
export function Bone({ className }: { className?: string }) {
  return (
    <span
      aria-hidden="true"
      className={cn("block animate-pulse rounded-xl bg-lilac-soft motion-reduce:animate-none", className)}
    />
  );
}

/** Esqueleto de una tarjeta de sección (mismo aspecto que StepCard). */
export function StepCardSkeleton() {
  return (
    <div className={cn(CARD, "flex items-center justify-between gap-4 px-5 py-5 sm:px-6")}>
      <div className="flex flex-1 flex-col gap-2.5">
        <Bone className="h-4 w-1/3" />
        <Bone className="h-3 w-2/3" />
      </div>
      <Bone className="h-6 w-24 rounded-full" />
    </div>
  );
}

function PlanShellSkeleton() {
  return (
    <div className="flex flex-col gap-6" role="status" aria-label="Cargando tu plan">
      <Bone className="h-10 w-2/3 max-w-sm bg-track" />
      <div className="flex gap-6 border-b border-line pb-3">
        {[0, 1, 2, 3, 4, 5].map((i) => (
          <Bone key={i} className="h-4 w-16 bg-track sm:w-20" />
        ))}
      </div>
      <div className={cn(CARD, "grid grid-cols-2 gap-4 px-4 py-3 sm:grid-cols-4 sm:px-5")}>
        {[0, 1, 2, 3].map((i) => (
          <div key={i} className="flex flex-col gap-2">
            <Bone className="h-3 w-1/3" />
            <Bone className="h-4 w-2/3" />
          </div>
        ))}
      </div>
      <div className="flex flex-col gap-3">
        {[0, 1, 2, 3].map((i) => (
          <StepCardSkeleton key={i} />
        ))}
      </div>
    </div>
  );
}

function PlanShellInner({ children }: { children: React.ReactNode }) {
  const { plan, loading, isMember } = usePlanContext();

  if (loading) {
    return <PlanShellSkeleton />;
  }

  if (!plan || !isMember) {
    return (
      <div className={cn(CARD, "mx-auto my-10 flex max-w-md flex-col items-center p-8 text-center")}>
        <IconCircle tone="lilac" className="size-12">
          <LockIcon />
        </IconCircle>
        <h1 className="mt-4 font-display text-xl font-semibold text-ink">
          No tienes acceso a este plan
        </h1>
        <p className="mt-2 text-sm text-ink-muted">
          Puede que el plan no exista o que aún no seas miembro. Pide al dueño del plan que te
          invite de nuevo.
        </p>
        <Link href="/dashboard" className={cn(CTA_SECONDARY, "mt-5")}>
          <ArrowLeftIcon aria-hidden="true" className="size-4" />
          Volver al inicio
        </Link>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex max-w-full flex-col items-start gap-2 self-start">
        <Link
          href="/dashboard"
          className={cn(
            FOCUS,
            "inline-flex h-9 items-center gap-1.5 rounded-full px-3.5 text-sm font-medium text-ink ring-1 ring-line-strong transition-colors hover:bg-lilac-soft hover:text-ink-strong motion-reduce:transition-none"
          )}
        >
          <ArrowLeftIcon aria-hidden="true" className="size-4" />
          Volver al inicio
        </Link>
        {/* Decorative: the plan's title is the couple's names, so it gets
            the script accent reserved for that one case. If it's ever
            autogenerated placeholder text instead, switch this back to a
            plain font-display heading. */}
        <h1 className="text-script-accent text-balance break-words" style={{ color: "var(--ink)" }}>
          {plan.title}
        </h1>
      </div>
      <PlanNav planId={plan.id} />
      {children}
    </div>
  );
}

export function PlanShell({
  planId,
  children,
}: {
  planId: string;
  children: React.ReactNode;
}) {
  return (
    <PlanProvider planId={planId}>
      <PlanShellInner>{children}</PlanShellInner>
    </PlanProvider>
  );
}
