"use client";

import * as React from "react";
import { LockIcon } from "lucide-react";

import { Sparkles } from "@/components/brand/hero-decorations";
import { CARD, IconCircle } from "@/components/dashboard/ui";
import { PlanProvider, usePlanContext } from "@/lib/context/plan-context";
import { PlanNav } from "@/components/plan/plan-nav";
import { cn } from "@/lib/utils";

/** Bloque de esqueleto: pulso suave que respeta prefers-reduced-motion. */
export function Bone({ className }: { className?: string }) {
  return (
    <span
      aria-hidden="true"
      className={cn("block animate-pulse rounded-xl bg-[#ECE6F4] motion-reduce:animate-none", className)}
    />
  );
}

/** Esqueleto de una tarjeta de sección (mismo aspecto que StepCard). */
export function StepCardSkeleton() {
  return (
    <div className={cn(CARD, "flex items-center justify-between gap-4 px-5 py-5 sm:px-6")}>
      <div className="flex flex-1 flex-col gap-2.5">
        <Bone className="h-4 w-1/3" />
        <Bone className="h-3 w-2/3" />
      </div>
      <Bone className="h-6 w-24 rounded-full" />
    </div>
  );
}

function PlanShellSkeleton() {
  return (
    <div className="flex flex-col gap-6" role="status" aria-label="Cargando tu plan">
      <Bone className="h-10 w-2/3 max-w-sm bg-[#E5DDEC]" />
      <div className="flex gap-6 border-b border-[#E5DDEC] pb-3">
        {[0, 1, 2, 3, 4].map((i) => (
          <Bone key={i} className="h-4 w-16 bg-[#E5DDEC] sm:w-20" />
        ))}
      </div>
      <div className={cn(CARD, "grid gap-5 p-5 sm:grid-cols-3 sm:p-6")}>
        {[0, 1, 2].map((i) => (
          <div key={i} className="flex items-center gap-3.5">
            <Bone className="size-10 shrink-0 rounded-full" />
            <div className="flex flex-1 flex-col gap-2.5">
              <Bone className="h-3 w-1/2" />
              <Bone className="h-5 w-3/4" />
            </div>
          </div>
        ))}
      </div>
      <div className="flex flex-col gap-3">
        {[0, 1, 2, 3].map((i) => (
          <StepCardSkeleton key={i} />
        ))}
      </div>
    </div>
  );
}

function PlanShellInner({ children }: { children: React.ReactNode }) {
  const { plan, loading, isMember } = usePlanContext();

  if (loading) {
    return <PlanShellSkeleton />;
  }

  if (!plan || !isMember) {
    return (
      <div className={cn(CARD, "mx-auto my-10 flex max-w-md flex-col items-center p-8 text-center")}>
        <IconCircle tone="lilac" className="size-12">
          <LockIcon />
        </IconCircle>
        <h1 className="mt-4 font-display text-xl font-semibold text-[#26413C]">
          No tienes acceso a este plan
        </h1>
        <p className="mt-2 text-sm text-[#586C64]">
          Puede que el plan no exista o que aún no seas miembro. Pide al dueño del plan que te
          invite de nuevo.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="relative max-w-full self-start pr-10">
        {/* Decorative: the plan's title is the couple's names, so it gets
            the script accent reserved for that one case. If it's ever
            autogenerated placeholder text instead, switch this back to a
            plain font-display heading. */}
        <h1 className="text-script-accent text-balance break-words" style={{ color: "#26413C" }}>
          {plan.title}
        </h1>
        <Sparkles className="-right-1 -top-3 size-9 sm:size-10" />
      </div>
      <PlanNav planId={plan.id} />
      {children}
    </div>
  );
}

export function PlanShell({
  planId,
  children,
}: {
  planId: string;
  children: React.ReactNode;
}) {
  return (
    <PlanProvider planId={planId}>
      <PlanShellInner>{children}</PlanShellInner>
    </PlanProvider>
  );
}
